export const dictionaries = {
  en: {
    menu:'Browse the menu', collection:'Explore the collection', all:'All products', search:'Search products...', share:'Share shop', favorites:'Favorites', order:'Place order', cart:'Order on WhatsApp', yourOrder:'Your order', type:'Order type', dine:'Dine in', takeaway:'Takeaway', delivery:'Delivery', table:'Table number', name:'Your name', phone:'Phone number', address:'Delivery address', coupon:'Coupon code', items:'Items subtotal', submit:'Place order', nothing:'Nothing is charged online.', back:'Back to menu', close:'Your order is empty.', add:'Add something from the menu.', shopClosed:'The shop is closed right now.', tagline:'Thoughtfully picked. Just for you.', install:'Install app', fresh:'New', outOfStock:'Out of stock', onlyLeft:'Only {n} left', view:'View product', bestseller:'Bestseller', talkKicker:'GOOD THINGS START WITH A CONVERSATION ✳', talkTitle:'Like something?', talkAccent:"Let's talk.", talkBody:"Pick a product and message us on WhatsApp. We'd love to hear from you.", callOwner:'Call owner', whatsappMsg:'WhatsApp message', productsCount:'PRODUCTS', empty:'Nothing here yet', emptyHint:'Try a different search or category.',
    cartTitle:'Your cart',cartEmpty:'Your cart is empty',cartEmptyHint:'Add items from the shop to order them together on WhatsApp.',myOrders:'My orders',subtotal:'Subtotal',deliveryLbl:'Delivery',freeLbl:'FREE',totalLbl:'Total',referral:'Referral code (optional)',couponOpt:'Coupon code (optional)',opening:'Opening WhatsApp...',noCharge:'Your order opens as a WhatsApp message to the shop. Nothing is charged online.',answerReq:'Please answer the required questions for {name}.'
  },
  hi: {
    menu:'मेन्यू देखें', collection:'सामान देखें', all:'सभी सामान', search:'सामान खोजें...', share:'दुकान शेयर करें', favorites:'पसंदीदा', order:'ऑर्डर करें', cart:'WhatsApp पर ऑर्डर करें', yourOrder:'आपका ऑर्डर', type:'ऑर्डर का प्रकार', dine:'यहीं बैठकर', takeaway:'साथ ले जाएँ', delivery:'होम डिलीवरी', table:'टेबल नंबर', name:'आपका नाम', phone:'फोन नंबर', address:'डिलीवरी का पता', coupon:'कूपन कोड', items:'सामान का कुल', submit:'ऑर्डर करें', nothing:'ऑनलाइन भुगतान नहीं लिया जाएगा।', back:'मेन्यू पर लौटें', close:'आपका ऑर्डर खाली है।', add:'मेन्यू से कुछ जोड़ें।', shopClosed:'अभी दुकान बंद है।', tagline:'ख़ास आपके लिए चुना हुआ।', install:'ऐप इंस्टॉल करें', fresh:'नया', outOfStock:'स्टॉक खत्म', onlyLeft:'सिर्फ़ {n} बचे', view:'सामान देखें', bestseller:'बेस्टसेलर', talkKicker:'अच्छी चीज़ें बातचीत से शुरू होती हैं ✳', talkTitle:'कुछ पसंद आया?', talkAccent:'बात करते हैं।', talkBody:'कोई सामान चुनें और WhatsApp पर हमें मैसेज करें। हमें आपसे बात करके खुशी होगी।', callOwner:'मालिक को कॉल करें', whatsappMsg:'WhatsApp मैसेज', productsCount:'सामान', empty:'यहाँ अभी कुछ नहीं है', emptyHint:'कोई दूसरी खोज या श्रेणी आज़माएँ।',
    cartTitle:'आपकी कार्ट',cartEmpty:'आपकी कार्ट खाली है',cartEmptyHint:'दुकान से सामान जोड़ें और एक साथ WhatsApp पर ऑर्डर करें।',myOrders:'मेरे ऑर्डर',subtotal:'उप-योग',deliveryLbl:'डिलीवरी',freeLbl:'मुफ़्त',totalLbl:'कुल',referral:'रेफ़रल कोड (वैकल्पिक)',couponOpt:'कूपन कोड (वैकल्पिक)',opening:'WhatsApp खुल रहा है...',noCharge:'आपका ऑर्डर दुकान को WhatsApp संदेश के रूप में खुलेगा। ऑनलाइन कोई शुल्क नहीं लगेगा।',answerReq:'{name} के लिए ज़रूरी सवालों के जवाब दें।'
  },
  mr: {
    menu:'मेनू पाहा', collection:'वस्तू पाहा', all:'सर्व वस्तू', search:'वस्तू शोधा...', share:'दुकान शेअर करा', favorites:'आवडते', order:'ऑर्डर करा', cart:'WhatsApp वर ऑर्डर करा', yourOrder:'तुमची ऑर्डर', type:'ऑर्डरचा प्रकार', dine:'इथेच बसून', takeaway:'घेऊन जा', delivery:'घरपोच', table:'टेबल क्रमांक', name:'तुमचे नाव', phone:'फोन नंबर', address:'डिलिव्हरीचा पत्ता', coupon:'कूपन कोड', items:'वस्तूंची एकूण रक्कम', submit:'ऑर्डर करा', nothing:'ऑनलाइन पेमेंट घेतले जाणार नाही.', back:'मेनूवर परत जा', close:'तुमची ऑर्डर रिकामी आहे.', add:'मेनूमधून काहीतरी जोडा.', shopClosed:'दुकान सध्या बंद आहे.', tagline:'खास तुमच्यासाठी निवडलेले.', install:'अ‍ॅप इन्स्टॉल करा', fresh:'नवीन', outOfStock:'स्टॉक संपला', onlyLeft:'फक्त {n} शिल्लक', view:'वस्तू पाहा', bestseller:'बेस्टसेलर', talkKicker:'चांगल्या गोष्टी संभाषणातून सुरू होतात ✳', talkTitle:'काही आवडले का?', talkAccent:'बोलूया.', talkBody:'एखादी वस्तू निवडा आणि आम्हाला WhatsApp वर मेसेज करा. तुमच्याशी बोलायला आवडेल.', callOwner:'मालकाला कॉल करा', whatsappMsg:'WhatsApp मेसेज', productsCount:'वस्तू', empty:'इथे अजून काही नाही', emptyHint:'दुसरा शोध किंवा श्रेणी वापरून पाहा.',
    cartTitle:'तुमची कार्ट',cartEmpty:'तुमची कार्ट रिकामी आहे',cartEmptyHint:'दुकानातून वस्तू जोडा आणि एकत्र WhatsApp वर ऑर्डर करा.',myOrders:'माझे ऑर्डर',subtotal:'उप-बेरीज',deliveryLbl:'डिलिव्हरी',freeLbl:'मोफत',totalLbl:'एकूण',referral:'रेफरल कोड (ऐच्छिक)',couponOpt:'कूपन कोड (ऐच्छिक)',opening:'WhatsApp उघडत आहे...',noCharge:'तुमचा ऑर्डर दुकानाला WhatsApp संदेश म्हणून उघडेल. ऑनलाइन कोणतेही शुल्क नाही.',answerReq:'{name} साठी आवश्यक प्रश्नांची उत्तरे द्या.'
  }
};
export const translate = (lang, key) => dictionaries[lang]?.[key] || dictionaries.en[key] || key;
