import React,{useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {api} from '../../shared/lib/api.js';
import {Logo} from '../../shared/components/chrome.jsx';
export default function SetPassword(){
 const [params]=useState(()=>new URLSearchParams(location.hash.slice(1)));const [form,setForm]=useState({newPassword:'',confirmPassword:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const nav=useNavigate();
 const submit=async e=>{e.preventDefault();setError('');if(form.newPassword!==form.confirmPassword){setError('New passwords do not match.');return;}setBusy(true);try{await api('/auth/set-password',{method:'POST',body:{...form,email:params.get('email'),token:params.get('token')},successMessage:'Password saved. You can now sign in.'});history.replaceState(null,'',location.pathname);nav('/login',{replace:true});}catch(err){setError(err.message);}finally{setBusy(false);}};
 return <main className="container" style={{maxWidth:560,padding:'40px 20px'}}><Logo/><section className="dashboard-panel password-settings"><h1>Choose your password</h1><p>{params.get('email')}</p><p className="muted">Your setup link works once and expires in 24 hours. Choose a password only you know.</p>{params.get('token')&&params.get('email')?<form className="password-change-form" onSubmit={submit}>{[['newPassword','New password'],['confirmPassword','Confirm new password']].map(([key,label])=><label key={key}>{label}<input type="password" autoComplete="new-password" required minLength={12} maxLength={72} disabled={busy} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<small className="muted">At least 12 characters, maximum 72 bytes.</small>{error&&<p role="alert" className="notice error">{error}</p>}<button className="btn btn-green" disabled={busy}>{busy?'Saving...':'Set password'}</button></form>:<p role="alert">Open the complete setup link from your welcome email. If it has expired, ask your platform admin for a new one.</p>}<Link to="/login">Back to sign in</Link></section></main>;
}
