import { ot } from '../../shared/lib/owner-i18n.js';
import React,{useState,useEffect} from 'react';
import {api} from '../../shared/lib/api.js';
import {Notice} from '../../shared/components/chrome.jsx';
export default function OfferCampaigns({token,storeId}){
 const root=`/owner/${storeId}/campaigns`,[data,setData]=useState(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(null),[suggestions,setSuggestions]=useState([]);
 const [channel,setChannel]=useState('email'),[ids,setIds]=useState([]),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[postalAddress,setPostalAddress]=useState(''),[checks,setChecks]=useState({cost:false,consent:false,template:false});
 const [contact,setContact]=useState({channel:'email',address:'',name:'',consentSource:'',consentAt:'',confirmConsent:false});
 const load=async()=>{try{setData(await api(root,{token,feedback:false}));}catch(e){setError(e.message);}};
 useEffect(()=>{setData(null);setReview(null);setIds([]);load();},[storeId]);
 const act=async(fn)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const reset=()=>{setReview(null);setChecks({cost:false,consent:false,template:false});};
 const audience=data?.contacts.filter(c=>c.channel===channel&&!c.suppressedAt)||[];
 return <div><Notice error={error} success={success}/><section className="dashboard-panel"><h3>{ot("Email & SMS offers")}</h3><p className="muted">{ot("Use this store's own provider in Shop settings. Offers need separate consent for email or SMS. An order, imported phone list or WhatsApp permission does not count. Provider fees and account reputation are your business's responsibility. Start with a small batch (up to 10 contacts); no automatic retries. Provider acceptance is not delivery.")}</p><p className="notice">{ot("Every offer includes a working opt-out link. Opted-out contacts stay suppressed per store and channel, even if added again. SMS STOP replies are not automatically read here: honor requests by suppressing the contact below, or use the opt-out link.")}</p>
 <div className="notify-two"><label>{ot("Channel")}<select value={channel} onChange={e=>{setChannel(e.target.value);setIds([]);reset();}}><option value="email">{ot("Email")}</option><option value="sms">{ot("SMS (paid)")}</option></select></label><div><strong>{ot("Provider")}</strong><p>{data?.providers[channel].configured?ot("{v0} - your business account", {v0: data.providers[channel].label}):ot("Not connected. Set it up in Shop settings.")}</p></div></div>
 {channel==='email'&&<><label>{ot("Offer subject")}<input maxLength={150} value={subject} onChange={e=>{setSubject(e.target.value);reset();}}/></label><label>{ot("Your business physical postal address")}<textarea rows={2} maxLength={400} value={postalAddress} onChange={e=>{setPostalAddress(e.target.value);reset();}} placeholder={ot("Used in the email footer. Do not invent an address.")}/></label></>}
 <label>{ot("Offer message")}<textarea rows={5} maxLength={channel==='sms'?180:4000} value={message} onChange={e=>{setMessage(e.target.value);reset();}} placeholder={ot("Write the offer, price/terms and expiry clearly.")}/></label><small>{message.length}/{channel==='sms'?180:4000}{ot(". Store name and opt-out link are added; long SMS may use multiple paid segments.")}</small>
 <h4>{ot("Choose consented contacts (")}{ids.length}/{data?.batchLimit||10} {ot("selected)")}</h4><div className="campaign-audience">{audience.map(c=><label className="check-label" key={c.id}><input type="checkbox" checked={ids.includes(c.id)} disabled={!ids.includes(c.id)&&ids.length>=(data?.batchLimit||10)} onChange={e=>{setIds(a=>e.target.checked?[...a,c.id]:a.filter(i=>i!==c.id));reset();}}/>{c.name||c.address} {c.name?`(${c.address})`:''}</label>)}</div>{!audience.length&&<p className="muted">{ot("No active")} {channel} {ot("offer contacts yet. Record real consent below; nothing is auto-enrolled.")}</p>}
 <button className="btn btn-green" disabled={busy||!ids.length||!data?.providers[channel].configured} onClick={()=>act(async()=>{setReview(await api(root+'/preview',{token,method:'POST',body:{channel,subject,message,postalAddress,contactIds:ids}}));})}>{ot("Review offer and audience")}</button>
 {review&&<div className="campaign-review" role="region" aria-label={ot("Review offer before send")}><h4>{ot("Review before sending")}</h4><p>{review.recipientCount} {ot("recipients via")} {review.channel}{ot(". Sender/provider:")} {review.sender}</p><p><strong>{review.subject}</strong></p><pre>{review.preview}</pre><details><summary>{ot("Exact recipients")}</summary>{review.recipients.map(c=><p key={c.id}>{c.name} {c.address}</p>)}</details><p>{review.notice}</p>{[['cost',ot("I approve use of my provider quota/balance and understand this may cost money.")],['consent',ot("These exact recipients agreed to offers from this business on this channel.")],['template',ot("I checked provider rules, sender and any required approved SMS template/variables match this message including the opt-out link.")]].map(([k,l])=><label className="check-label" key={k}><input type="checkbox" checked={checks[k]} onChange={e=>setChecks(c=>({...c,[k]:e.target.checked}))}/>{l}</label>)}<button className="btn btn-green" disabled={busy||!Object.values(checks).every(Boolean)} onClick={()=>act(async()=>{const r=await api(root+`/${review.id}/send`,{token,method:'POST',body:{confirmCosts:true,confirmConsent:true,confirmTemplate:true},feedback:false});setSuccess(ot("Campaign finished: {v0} provider accepted. Other recipients: {v1}. Check history; do not resend unknown outcomes.", {v0: r.results.filter(x=>x.status==='accepted').length, v1: r.results.filter(x=>x.status!=='accepted').length}));reset();await load();})}>{busy?ot("Sending once..."):ot("Send this reviewed offer once")}</button></div>}
 </section>
 <section className="dashboard-panel"><h3>{ot("Offer contacts & suppression")}</h3><p className="muted">{ot("Add only a customer/contact from this store with channel-specific consent evidence. Suppression cannot be undone here.")}</p><button className="btn btn-outline btn-small" disabled={busy} onClick={()=>act(async()=>setSuggestions((await api(root+'/suggestions',{token})).suggestions))}>{ot("Find this store's order contacts (no consent inferred)")}</button>{suggestions.length>0&&<div className="campaign-audience">{suggestions.map((s,i)=><button className="chip-btn" key={i} onClick={()=>setContact({...contact,...s,confirmConsent:false})}>{s.name||s.address} - {s.channel}</button>)}</div>}
 <form onSubmit={e=>{e.preventDefault();act(async()=>{await api(root+'/contacts',{token,method:'POST',body:{...contact,consentAt:new Date(contact.consentAt).toISOString()}});setContact({channel:'email',address:'',name:'',consentSource:'',consentAt:'',confirmConsent:false});await load();});}}><div className="notify-two"><label>{ot("Consent channel")}<select value={contact.channel} onChange={e=>setContact({...contact,channel:e.target.value,confirmConsent:false})}><option value="email">{ot("Email")}</option><option value="sms">{ot("SMS")}</option></select></label><label>{ot("Email or Indian mobile")}<input required value={contact.address} maxLength={160} onChange={e=>setContact({...contact,address:e.target.value,confirmConsent:false})}/></label></div><label>{ot("Customer name")}<input value={contact.name} maxLength={100} onChange={e=>setContact({...contact,name:e.target.value})}/></label><label>{ot("Consent evidence / source")}<input required value={contact.consentSource} maxLength={200} onChange={e=>setContact({...contact,consentSource:e.target.value})} placeholder={ot("Where and how they agreed specifically to email or SMS offers")}/></label><label>{ot("When they agreed")}<input type="datetime-local" required value={contact.consentAt} onChange={e=>setContact({...contact,consentAt:e.target.value})}/></label><label className="check-label"><input required type="checkbox" checked={contact.confirmConsent} onChange={e=>setContact({...contact,confirmConsent:e.target.checked})}/> {ot("This person agreed to promotional offers from this store on the selected channel.")}</label><button className="btn btn-green" disabled={busy}>{ot("Save consented contact")}</button></form>
 <div className="table-wrap"><table><thead><tr><th>{ot("Contact")}</th><th>{ot("Channel")}</th><th>{ot("Consent source")}</th><th>{ot("Status")}</th><th>{ot("Action")}</th></tr></thead><tbody>{data?.contacts.map(c=><tr key={c.id}><td>{c.name}<small>{c.address}</small></td><td>{c.channel}</td><td>{c.consentSource}</td><td>{c.suppressedAt?ot("Opted out"):ot("Consented")}</td><td>{!c.suppressedAt&&<button className="btn btn-outline btn-small" disabled={busy} onClick={()=>act(async()=>{await api(root+`/contacts/${c.id}/suppress`,{token,method:'POST',body:{}});setIds(a=>a.filter(i=>i!==c.id));reset();await load();})}>{ot("Suppress")}</button>}</td></tr>)}</tbody></table></div>
 </section><section className="dashboard-panel table-wrap"><h3>{ot("Campaign history")}</h3><p className="muted">{ot("Accepted = provider accepted, not verified delivery. Interrupted campaigns stay sending; never blindly retry them.")}</p><table><thead><tr><th>{ot("Created")}</th><th>{ot("Channel / subject")}</th><th>{ot("Status")}</th><th>{ot("Outcomes")}</th></tr></thead><tbody>{data?.campaigns.map(c=><tr key={c.id}><td>{new Date(c.createdAt).toLocaleString()}</td><td>{c.channel} {c.subject}</td><td>{c.status}</td><td><details><summary>{c.results.filter(r=>r.status==='accepted').length} {ot("accepted /")} {c.results.length} {ot("recorded")}</summary>{c.results.map((r,i)=><p key={i}>{r.address}: {r.status} {r.error}</p>)}</details></td></tr>)}</tbody></table></section></div>;
}
export function OfferOptOut(){const [state,setState]=useState(null),[error,setError]=useState('');const token=location.pathname.split('/').pop();useEffect(()=>{const meta=document.createElement('meta');meta.name='referrer';meta.content='no-referrer';document.head.appendChild(meta);api(`/public/offers/opt-out/${token}`,{feedback:false}).then(setState).catch(e=>setError(e.message));return()=>meta.remove();},[token]);return <main className="container" style={{maxWidth:600,paddingTop:80}}><h1>{ot("Stop store offers")}</h1>{error?<p>{ot(error)}</p>:!state?<p>{ot("Checking link...")}</p>:state.suppressed?<p>{ot("You are opted out of this store's")} {state.channel} {ot("offers. This does not change order updates you requested.")}</p>:<><p>{ot("Stop future")} {state.channel} {ot("offers from this store? No sign-in needed.")}</p><button className="btn btn-green" onClick={async()=>{try{await api(`/public/offers/opt-out/${token}`,{method:'POST',body:{},feedback:false});setState({...state,suppressed:true});}catch(e){setError(e.message);}}}>{ot("Stop offers")}</button></>}</main>;}
