import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
for(const lang of ['en','hi','mr']){
 const context=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});await context.addInitScript(({lang})=>{if(!localStorage.getItem('dd-storefront-language:guest'))localStorage.setItem('dd-storefront-language:guest',lang);localStorage.setItem('dd-theme','light')},{lang});const page=await context.newPage();const errors=[];page.on('pageerror',e=>console.log('PAGEERROR',e.message),errors.push(e.message));
 await page.route('**/api/public/stores/demo-shop/products*',r=>r.fulfill({json:{products:[],total:0,page:1}}));await page.goto('http://127.0.0.1:4173/store/demo-shop');await page.waitForTimeout(500);await expect(page.locator('.empty-state')).toBeVisible();await page.screenshot({path:`/tmp/storefront-${lang}-empty.png`,fullPage:true});
 await page.locator('.store-banner-actions button').nth(1).click();await page.screenshot({path:`/tmp/storefront-${lang}-empty-favorites.png`,fullPage:true});await page.locator('.drawer-head button').click();
 await page.route('**/api/public/stores/demo-shop',async route=>{const response=await route.fetch(),data=await response.json();data.business.isOpen=false;data.business.blocksOrders=true;await route.fulfill({json:data})});await page.reload();await expect(page.locator('.closed-banner')).toBeVisible();await page.screenshot({path:`/tmp/storefront-${lang}-closed.png`,fullPage:true});
 await page.route('**/api/public/stores/demo-shop/products/1',r=>r.fulfill({status:404,json:{error:'Product not found'}}));await page.goto('http://127.0.0.1:4173/store/demo-shop/product/1');await expect(page.locator('.empty-state')).toContainText(lang==='en'?'Product not found':lang==='hi'?'उत्पाद':'उत्पादन');await page.screenshot({path:`/tmp/storefront-${lang}-error.png`,fullPage:true});
 await page.evaluate(()=>{localStorage.setItem('dd-storefront-language:guest','mr');window.dispatchEvent(new StorageEvent('storage',{key:'dd-storefront-language:guest'}))});await expect(page.locator('.header-controls select')).toHaveValue('mr');
 await page.evaluate(()=>{localStorage.setItem('dd-session',JSON.stringify({token:'mock',user:{id:999,name:'Account',role:'owner'}}))});await page.reload();await expect(page.locator('.header-controls select')).toHaveValue('en');await page.locator('.header-controls select').selectOption('hi');await page.evaluate(()=>localStorage.removeItem('dd-session'));await page.reload();await expect(page.locator('.header-controls select')).toHaveValue('mr');
 expect(errors).toEqual([]);console.log('PASS',lang,'empty/error/closed and storage/account isolation');await context.close();
}
await browser.close();
