import test from 'node:test';
import assert from 'node:assert/strict';
import jwt from 'jsonwebtoken';
process.env.DATABASE_URL='postgres://sandbox@127.0.0.1:55432/dd_crm_test';
process.env.DATABASE_SSL='false';
process.env.JWT_SECRET='isolated-test-secret-32-characters-long';
const {default:app}=await import('../../app.js');
const {sequelize,User,Business,Category,Product,Lead}=await import('../../models/index.js');
const {Customer,ensureCrmSchema}=await import('./crm.js');
test('real Postgres CRM, undo, consent, tenant boundaries and existing retail routes',async()=>{
 await sequelize.sync({force:true});
 const a=await User.create({name:'Test Owner A',email:'a@test.invalid',passwordHash:'test',role:'owner'});
 const b=await User.create({name:'Test Owner B',email:'b@test.invalid',passwordHash:'test',role:'owner'});
 const store=await Business.create({ownerId:a.id,name:'Test A',slug:'local-test-a',whatsapp:'919876543210'});
 const other=await Business.create({ownerId:b.id,name:'Test B',slug:'local-test-b',whatsapp:'919876543211'});
 const staff=await User.create({name:'Staff',email:'staff@test.invalid',passwordHash:'test',role:'staff',managerId:a.id,staffBusinessId:store.id});
 const category=await Category.create({businessId:store.id,name:'Food',slug:'food'});
 await Product.create({businessId:store.id,categoryId:category.id,name:'Rice',price:120});
 const server=app.listen(0);const base=`http://127.0.0.1:${server.address().port}/api`;
 const call=async(path,method='GET',body,actor=a)=>{const r=await fetch(base+path,{method,headers:{authorization:`Bearer ${jwt.sign({sub:actor.id},process.env.JWT_SECRET)}`,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
 const root=`/owner/${store.id}/customers`;
 try {
  delete process.env.CRM_ENABLED;
  assert.equal((await call(root)).status,404);
  const retailBefore=(await call('/public/stores/local-test-a')).body;
  assert.equal((await call('/owner/stores')).status,200);
  process.env.CRM_ENABLED='true';await ensureCrmSchema();
  let result=await call(root,'POST',{phone:'+91 9876543210',name:'Existing'});assert.equal(result.status,201);const original=result.body.customer;
  assert.equal(original.optInStatus,'unknown');
  assert.equal((await call(`/owner/${other.id}/customers`)).status,404);
  assert.equal((await call(root,'GET',null,staff)).status,403);
  assert.equal((await call(root,'POST',{phone:'919876543210'})).status,409);
  const rows=[{phone:'919876543210',name:'Duplicate'},{phone:'919876543212',name:'Imported One',optInStatus:'opted_in'},{phone:'919876543213',name:'Imported Two'}];
  result=await call(root+'/import/preview','POST',{rows});assert.equal(result.status,200);assert.equal(result.body.newCount,2);assert.equal(result.body.duplicateCount,1);const digest=result.body.digest;
  assert.equal(await Customer.count(),1,'preview is a dry run');
  assert.equal((await call(root+'/import/commit','POST',{rows,digest:'tampered'})).status,400);
  result=await call(root+'/import/commit','POST',{rows,digest});assert.equal(result.status,201);assert.equal(result.body.created,2);assert.equal(result.body.skipped,1);const batch=result.body.batchId;
  const imported=await Customer.findOne({where:{phone:'919876543212'}});assert.equal(imported.optInStatus,'unknown');
  assert.equal((await call(root+`/${imported.id}`,'PATCH',{name:'Edited after import'})).status,200);
  assert.equal((await call(`/owner/${other.id}/customers/import/${batch}/undo`,'POST',{},b)).status,404);
  result=await call(root+`/import/${batch}/undo`,'POST',{});assert.equal(result.status,200);assert.deepEqual(result.body,{removed:1,retained:1});
  assert.equal((await call(root+`/import/${batch}/undo`,'POST',{})).status,409);
  assert.equal(await Customer.count(),2);
  result=await call(root+`/${original.id}`,'PATCH',{optInStatus:'opted_out'});assert.equal(result.status,200);
  assert.equal((await call(root+`/${original.id}`,'PATCH',{optInStatus:'unknown'})).status,409);
  assert.equal((await call(root+`/${original.id}`,'PATCH',{optInStatus:'opted_in',optInPurpose:'Updates',optInSource:'Form',optInAt:'2026-01-01T00:00:00Z'})).status,409);
  assert.equal((await call(root+'?q=Edited&status=unknown')).body.customers.length,1);
  assert.deepEqual((await call('/public/stores/local-test-a')).body,retailBefore,'CRM leaves storefront read unchanged');
  assert.equal((await call('/owner/stores')).status,200);
  const many=Array.from({length:500},(_,i)=>({phone:String(918000000000+i),name:`Bulk ${i}`}));
  assert.equal((await call(root+'/import/preview','POST',{rows:[...many,{phone:'919000000001'}]})).status,400);
  const bulkPreview=await call(root+'/import/preview','POST',{rows:many});assert.equal(bulkPreview.body.newCount,500);
  const bulk=await call(root+'/import/commit','POST',{rows:many,digest:bulkPreview.body.digest});assert.equal(bulk.status,201);assert.equal(bulk.body.created,500);
  const firstPage=await call(root);const lastPage=await call(root+'?page=11');assert.equal(firstPage.body.total,502);assert.equal(firstPage.body.customers.length,50);assert.equal(lastPage.body.customers.length,2);
  assert.equal((await call(root+'?page=-1')).status,400);
  assert.equal((await call(root+`/${original.id}`,'DELETE',null,staff)).status,403);
  assert.equal((await call(`/owner/${other.id}/customers/${original.id}`,'DELETE',null,b)).status,404);
  assert.equal((await call(root+`/${original.id}`,'DELETE')).status,200);
  assert.equal((await call(root+'?q=Existing')).body.total,0);
  assert.equal((await Customer.findByPk(original.id)).optInStatus,'opted_out');
  assert.equal((await call(root,'POST',{phone:original.phone})).status,409,'removal cannot erase suppression');
  assert.equal((await call(root+`/${original.id}`,'PATCH',{optInStatus:'unknown'})).status,404);
  assert.equal((await call(root+`/import/${bulk.body.batchId}/undo`,'POST',{})).body.removed,500);
  await Lead.create({ businessId:store.id, productName:'2 items', price:390, items:[{name:'Rice',qty:1,price:180},{name:'Oil',qty:1,price:220}], discount:40, couponCode:'QA10', status:'confirmed' });
  const csvResponse=await fetch(base+`/owner/${store.id}/export/vyapar.csv`,{headers:{authorization:`Bearer ${jwt.sign({sub:a.id},process.env.JWT_SECRET)}`}});
  assert.equal(csvResponse.status,200);const csv=await csvResponse.text();assert.ok(csv.includes('Coupon discount (QA10)'));assert.ok(csv.includes('Delivery charge'));
  const csvTotal=csv.trim().split('\n').slice(1).reduce((sum,line)=>sum+Number(line.split(',')[8].replaceAll('"','')),0);assert.equal(csvTotal,390);
  delete process.env.CRM_ENABLED;assert.equal((await call(root)).status,404);assert.deepEqual((await call('/public/stores/local-test-a')).body,retailBefore,'instant flag off preserves retail');
  const {purgeExpiredStore}=await import('../../shared/retention.js');
  await store.update({deletedAt:new Date('2026-01-01'),active:false});
  process.env.STORE_SUBDOMAINS_READY='false';
  const originalFetch=globalThis.fetch;const originalDomainToken=process.env.VERCEL_STORE_DOMAIN_TOKEN;
  globalThis.fetch=async()=>({ok:true,status:204});process.env.VERCEL_STORE_DOMAIN_TOKEN='local-test-only';
  try { const purged=await purgeExpiredStore(new Date('2026-09-30'));assert.equal(purged.purged,1); } finally {globalThis.fetch=originalFetch;if(originalDomainToken===undefined)delete process.env.VERCEL_STORE_DOMAIN_TOKEN;else process.env.VERCEL_STORE_DOMAIN_TOKEN=originalDomainToken;}
  assert.equal(await Customer.count({where:{businessId:store.id}}),0,'purge removes CRM data even after CRM flag off');
 } finally {await new Promise(resolve=>server.close(resolve));await sequelize.close();}
});
