import {Router} from 'express';
import {DataTypes,Op} from 'sequelize';
import {randomBytes,createHash} from 'node:crypto';
import {sequelize,Business,Lead,RestaurantOrder} from './models/index.js';
import {bad,wrap,validEmail,clientBase} from './utils/core.js';
import {resolveDeps,providerStatus,sendEmail,sendSms,indianMobile} from './notify.js';
const channelType=DataTypes.STRING(8);
export const OfferContact=sequelize.define('OfferContact',{businessId:{type:DataTypes.INTEGER,allowNull:false},channel:{type:channelType,allowNull:false},address:{type:DataTypes.STRING(160),allowNull:false},name:{type:DataTypes.STRING(100),defaultValue:''},consentSource:{type:DataTypes.STRING(200),allowNull:false},consentAt:{type:DataTypes.DATE,allowNull:false},suppressedAt:DataTypes.DATE,token:{type:DataTypes.STRING(48),allowNull:false,unique:true}},{tableName:'offer_contacts',indexes:[{unique:true,fields:['businessId','channel','address']}]});
export const OfferCampaign=sequelize.define('OfferCampaign',{businessId:{type:DataTypes.INTEGER,allowNull:false},channel:{type:channelType,allowNull:false},subject:DataTypes.STRING(150),message:{type:DataTypes.TEXT,allowNull:false},postalAddress:DataTypes.STRING(400),audience:{type:DataTypes.JSONB,allowNull:false},status:{type:DataTypes.STRING(20),defaultValue:'review'},results:{type:DataTypes.JSONB,defaultValue:[]},providerFingerprint:DataTypes.STRING(64),createdBy:DataTypes.INTEGER},{tableName:'offer_campaigns'});
let ready;export const ensureCampaignSchema=()=>ready ||= Promise.all([OfferContact.sync(),OfferCampaign.sync()]).catch(e=>{ready=null;throw e;});
export function normalizeOfferAddress(channel,address){if(!['email','sms'].includes(channel))throw bad(400,'Choose email or SMS');const a=String(address||'').trim();if(channel==='email'){if(a.length>160||!validEmail(a))throw bad(400,'Enter a valid email');return a.toLowerCase();}const n=indianMobile(a);if(!n)throw bad(400,'Use a valid Indian mobile number for SMS');return n;}
export function consentInput(input){const channel=input.channel,address=normalizeOfferAddress(channel,input.address),source=String(input.consentSource||'').trim(),at=new Date(input.consentAt);if(!source||source.length>200||!Number.isFinite(+at)||+at>Date.now()||input.confirmConsent!==true)throw bad(400,'Record consent source, past date/time and confirm this person agreed to offers on this channel');return {channel,address,name:String(input.name||'').trim().slice(0,100),consentSource:source,consentAt:at};}
export const OFFER_BATCH_LIMIT=10;
export function validateOfferProvider(p){if(!p)throw bad(400,'Connect this store\'s own provider first');if(p.kind==='smtp')throw bad(400,'Offers need an HTTPS email provider on this hosting. Use Resend or Email API.');if(p.kind==='http'){const template=`${p.url||''} ${p.body||''}`;if(!/\{\{\s*message\s*\}\}/i.test(template)||!/\{\{\s*to(?:_intl)?\s*\}\}/i.test(template))throw bad(400,'Offer API template must include {{message}} (with the opt-out link) and {{to}} or {{to_intl}}.');}}
const providerFingerprint=p=>createHash('sha256').update(JSON.stringify(p)).digest('hex');
const unsub=c=>`${clientBase()}/offers/opt-out/${c.token}`;
export const campaignOwnerRoutes=Router({mergeParams:true});
campaignOwnerRoutes.use((req,res,next)=>req.user.role==='owner'?next():res.status(403).json({error:'Only the store owner can manage campaigns'}));
campaignOwnerRoutes.use(wrap(async(req,res,next)=>{await ensureCampaignSchema();next();}));
campaignOwnerRoutes.get('/',wrap(async(req,res)=>{const id=req.store.id;const [contacts,campaigns,deps]=await Promise.all([OfferContact.findAll({where:{businessId:id},attributes:{exclude:['token']},order:[['createdAt','DESC']],limit:1000}),OfferCampaign.findAll({where:{businessId:id},attributes:{exclude:['audience','providerFingerprint']},order:[['createdAt','DESC']],limit:30}),resolveDeps(req.store)]);res.json({contacts,campaigns,providers:providerStatus(deps.providers),batchLimit:OFFER_BATCH_LIMIT});}));
campaignOwnerRoutes.get('/suggestions',wrap(async(req,res)=>{const where={businessId:req.store.id};const attrs=['customerName','customerPhone','customerEmail'];const [leads,orders]=await Promise.all([Lead.findAll({where,attributes:attrs,order:[['createdAt','DESC']],limit:100}),RestaurantOrder.findAll({where,attributes:attrs,order:[['createdAt','DESC']],limit:100})]);const seen=new Set(),items=[];for(const o of [...leads,...orders])for(const channel of ['email','sms']){try{const address=normalizeOfferAddress(channel,channel==='email'?o.customerEmail:o.customerPhone),key=channel+address;if(!seen.has(key)){seen.add(key);items.push({channel,address,name:o.customerName||''});}}catch{}}res.json({suggestions:items,notice:'Order contacts are suggestions, never marketing consent. Add only with separate permission.'});}));
campaignOwnerRoutes.post('/contacts',wrap(async(req,res)=>{const fields=consentInput(req.body||{});const [c,created]=await OfferContact.findOrCreate({where:{businessId:req.store.id,channel:fields.channel,address:fields.address},defaults:{...fields,token:randomBytes(24).toString('hex')}});if(!created)throw bad(409,c.suppressedAt?'This contact opted out. Suppression cannot be cleared by adding it again.':'Contact already exists');res.status(201).json({id:c.id});}));
campaignOwnerRoutes.post('/contacts/:id/suppress',wrap(async(req,res)=>{const c=await OfferContact.findOne({where:{id:req.params.id,businessId:req.store.id}});if(!c)throw bad(404,'Contact not found');if(!c.suppressedAt)await c.update({suppressedAt:new Date()});res.json({ok:true});}));
campaignOwnerRoutes.post('/preview',wrap(async(req,res)=>{const b=req.body||{},channel=b.channel;if(!['email','sms'].includes(channel))throw bad(400,'Choose email or SMS');const deps=await resolveDeps(req.store);if(!deps.providers[channel])throw bad(400,'Connect this store\'s own provider in Shop settings first');validateOfferProvider(deps.providers[channel]);
const message=String(b.message||'').trim(),subject=String(b.subject||'').trim(),postalAddress=String(b.postalAddress||'').trim();if(!message||message.length>(channel==='sms'?180:4000)||/[\r\n]/.test(subject)||subject.length>150)throw bad(400,'Enter a message within the character limit');if(channel==='email'&&(!subject||!postalAddress||postalAddress.length>400))throw bad(400,'Email offers need a clear subject and your business postal address');
const ids=Array.isArray(b.contactIds)?[...new Set(b.contactIds.map(Number))]:[];if(!ids.length||ids.length>OFFER_BATCH_LIMIT||ids.some(n=>!Number.isSafeInteger(n)||n<1))throw bad(400,'Choose 1–10 opted-in contacts');const contacts=await OfferContact.findAll({where:{id:{[Op.in]:ids},businessId:req.store.id,channel,suppressedAt:null}});if(contacts.length!==ids.length)throw bad(400,'Audience includes contacts without active consent for this store/channel');
const example=contacts[0];if(channel==='sms'&&`Offer from ${req.store.name}\n${message}\nStop offers: ${unsub(example)}`.length>300)throw bad(400,'Shorten the SMS so the store name and real opt-out link fit within 300 characters');const campaign=await OfferCampaign.create({businessId:req.store.id,channel,subject,message,postalAddress,audience:contacts.map(c=>({id:c.id,address:c.address,name:c.name})),providerFingerprint:providerFingerprint(deps.providers[channel]),createdBy:req.user.id});res.status(201).json({id:campaign.id,channel,subject,recipientCount:contacts.length,recipients:campaign.audience,sender:deps.providers[channel].from||deps.providers[channel].senderId||deps.providers[channel].label,preview:`Offer from ${req.store.name}\n${message}${channel==='email'?`\n\n${postalAddress}`:''}\nStop offers: ${unsub(example)}`,notice:'Each recipient gets their own working opt-out link. Provider quota/charges apply to your business. Accepted is not delivered; failed/unknown sends are not retried.'});}));
campaignOwnerRoutes.post('/:id/send',wrap(async(req,res)=>{if(req.body?.confirmCosts!==true||req.body?.confirmConsent!==true||req.body?.confirmTemplate!==true)throw bad(400,'Review recipients/content, costs and provider-approved message requirements before sending');const campaign=await sequelize.transaction(async transaction=>{await Business.findByPk(req.store.id,{transaction,lock:transaction.LOCK.UPDATE});const recent=await OfferCampaign.findOne({where:{businessId:req.store.id,status:{[Op.in]:['sending','finished']},updatedAt:{[Op.gt]:new Date(Date.now()-60000)}},transaction});if(recent)throw bad(429,'Wait at least one minute between batches. Check history for any sending campaign first.');const c=await OfferCampaign.findOne({where:{id:req.params.id,businessId:req.store.id},transaction,lock:transaction.LOCK.UPDATE});if(!c)throw bad(404,'Campaign not found');if(c.status!=='review')throw bad(409,'Already started. Do not send this campaign again.');const deps=await resolveDeps(req.store);if(!deps.providers[c.channel])throw bad(400,'Your provider is not connected');validateOfferProvider(deps.providers[c.channel]);if(c.providerFingerprint!==providerFingerprint(deps.providers[c.channel]))throw bad(409,'Provider changed since review. Create a new review before sending.');await c.update({status:'sending'},{transaction});return c;});
const deps=await resolveDeps(req.store),results=[],started=Date.now();if(campaign.providerFingerprint!==providerFingerprint(deps.providers[campaign.channel])){await campaign.update({status:'finished',results:[{status:'not_sent',error:'Provider changed'}]});throw bad(409,'Provider changed. No messages sent.');}for(const a of campaign.audience){if(Date.now()-started>20000){results.push({address:a.address,status:'not_sent',error:'Batch time limit. Create a new review for unsent contacts.'});continue;}const c=await OfferContact.findOne({where:{id:a.id,businessId:req.store.id,channel:campaign.channel,address:a.address,suppressedAt:null}});if(!c){results.push({address:a.address,status:'suppressed'});continue;}
const text=`Offer from ${req.store.name}\n${campaign.message}${campaign.channel==='email'?`\n\n${campaign.postalAddress}`:''}\nStop offers: ${unsub(c)}`;if(campaign.channel==='sms'&&text.length>300){results.push({address:c.address,status:'failed',error:'SMS plus opt-out link exceeds 300 characters'});continue;}
results.push({address:c.address,status:'submitting'});await campaign.update({results:[...results]});
const result=campaign.channel==='email'?await sendEmail({to:c.address,subject:campaign.subject,text,store:req.store.name},deps):await sendSms({to:c.address,text,store:req.store.name},deps);results[results.length-1]={address:c.address,status:result.ok?'accepted':'unconfirmed',error:result.ok?'':result.error||result.skipped};await campaign.update({results:[...results]});}
await campaign.update({status:'finished',results:[...results]});res.json({id:campaign.id,status:campaign.status,results});}));
export const campaignPublicRoutes=Router();
campaignPublicRoutes.use('/offers/opt-out/:token',(req,res,next)=>{res.set('Cache-Control','no-store');res.set('Referrer-Policy','no-referrer');next();});
campaignPublicRoutes.get('/offers/opt-out/:token',wrap(async(req,res)=>{await ensureCampaignSchema();const c=await OfferContact.findOne({where:{token:req.params.token}});if(!c)throw bad(404,'Opt-out link unavailable');res.json({channel:c.channel,suppressed:!!c.suppressedAt});}));
campaignPublicRoutes.post('/offers/opt-out/:token',wrap(async(req,res)=>{await ensureCampaignSchema();const c=await OfferContact.findOne({where:{token:req.params.token}});if(!c)throw bad(404,'Opt-out link unavailable');if(!c.suppressedAt)await c.update({suppressedAt:new Date()});res.json({ok:true});}));
