import test from 'node:test';import assert from 'node:assert/strict';import {notifyNewProduct} from './new-product-push.js';
const store={id:11,name:'Ashiya',slug:'ashiya'};const product={id:91,businessId:11,name:'Ring',price:499,active:true,stock:2};
test('zero subscribers silently skips send even when push keys absent',async()=>{let sends=0;let where;const r=await notifyNewProduct({store,product,PushSubscription:{findAll:async q=>{where=q.where;return[];}},send:async()=>sends++,configured:false});assert.deepEqual(where,{businessId:11});assert.deepEqual(r,{sent:0,total:0});assert.equal(sends,0);});
test('only exact store audience gets approved payload and stale subscriptions removed',async()=>{const messages=[];let gone=0;const subs=[{endpoint:'good',keys:{}},{endpoint:'gone',keys:{},destroy:async()=>gone++}];const r=await notifyNewProduct({store,product,PushSubscription:{findAll:async q=>{assert.deepEqual(q.where,{businessId:11});return subs;}},send:async(s,p)=>{messages.push(JSON.parse(p));if(s.endpoint==='gone')throw{statusCode:410};},configured:true});assert.equal(r.sent,1);assert.equal(gone,1);assert.deepEqual(messages[0],{title:'New launch at Ashiya',body:'Ring - ₹499. Tap to view.',url:'/store/ashiya/product/91',icon:'/icon-192.png',badge:'/icon-192.png'});});
test('hidden and out-of-stock products never query or notify',async()=>{for(const p of [{...product,active:false},{...product,stock:0}]){const r=await notifyNewProduct({store,product:p,PushSubscription:{findAll:async()=>{throw Error('must not query');}},configured:true});assert.equal(r.skipped,true);}});
test('push failure never fails product creation and missing configuration sends nothing',async()=>{const r=await notifyNewProduct({store,product,PushSubscription:{findAll:async()=>{throw Error('db');}},configured:true});assert.equal(r.error,true);let sends=0;const q=await notifyNewProduct({store,product,PushSubscription:{findAll:async()=>[{}]},send:async()=>sends++,configured:false});assert.equal(q.skipped,true);assert.equal(sends,0);});
test('cross-store product is never disclosed',async()=>{const r=await notifyNewProduct({store,product:{...product,businessId:12},PushSubscription:{findAll:async()=>{throw Error('must not query');}},configured:true});assert.equal(r.skipped,true);});

test('product photo and store logo use safe public HTTPS URLs, gallery is fallback',async()=>{
 for(const [photo,gallery,expected] of [['https://ik.imagekit.io/a/product.jpg',[], 'https://ik.imagekit.io/a/product.jpg'],['', ['https://ik.imagekit.io/a/gallery.jpg'],'https://ik.imagekit.io/a/gallery.jpg'],['/uploads/a.png',[],'https://api.digitalshop.website/uploads/a.png']]){
 let payload;await notifyNewProduct({store:{...store,logoUrl:'https://ik.imagekit.io/a/logo.png'},product:{...product,imageUrl:photo,imageUrls:gallery},PushSubscription:{findAll:async()=>[{endpoint:'ok',keys:{}}]},send:async(s,p)=>payload=JSON.parse(p),configured:true});assert.equal(payload.image,expected);assert.equal(payload.icon,'https://ik.imagekit.io/a/logo.png');assert.equal(payload.badge,'/icon-192.png');
 }
});
test('unsafe image URLs are excluded and no-logo store keeps platform icon',async()=>{
 for(const photo of ['javascript:alert(1)','http://example.com/p.jpg','https://u:p@example.com/a']){let payload;await notifyNewProduct({store,product:{...product,imageUrl:photo},PushSubscription:{findAll:async()=>[{endpoint:'ok',keys:{}}]},send:async(s,p)=>payload=JSON.parse(p),configured:true});assert.equal(payload.image,undefined);assert.equal(payload.icon,'/icon-192.png');}
 let payload;await notifyNewProduct({store,product:{...product,imageUrl:'https://ik.imagekit.io/a/p.jpg'},PushSubscription:{findAll:async()=>[{endpoint:'ok',keys:{}}]},send:async(s,p)=>payload=JSON.parse(p),configured:true});assert.equal(payload.icon,'/icon-192.png');
});
