import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
process.env.DATABASE_URL||='postgres://local:local@localhost:5432/test';process.env.JWT_SECRET||='test-secret-must-be-at-least-32-characters-long';
const {default:app}=await import('./app.js');const {Business,User}=await import('./models/index.js');const {default:jwt}=await import('jsonwebtoken');
test('upload route sends the smaller image to hosting, without writing product/store rows',async()=>{
 const oldUser=User.findByPk;User.findByPk=async()=>({id:2,role:'owner',active:true});const oldFind=Business.findOne,oldFetch=global.fetch,oldKey=process.env.IMAGEKIT_PRIVATE_KEY;Business.findOne=async()=>({id:12,ownerId:2,active:true,deletedAt:null,featureLocks:{}});process.env.IMAGEKIT_PRIVATE_KEY='qa-only';let captured;
 global.fetch=async(u,o)=>{if(String(u).startsWith('https://upload.imagekit.io')){captured=o.body;return new Response(JSON.stringify({url:'https://ik.imagekit.io/qa/optimized.webp'}),{headers:{'content-type':'application/json'}});}return oldFetch(u,o);};const server=app.listen(0);
 try{const buffer=await sharp({create:{width:3200,height:1600,channels:4,background:{r:20,g:120,b:80,alpha:.5}}}).png().toBuffer();const form=new FormData();form.append('image',new Blob([buffer],{type:'image/png'}),'qa.png');const token=jwt.sign({sub:2,role:'owner',active:true},process.env.JWT_SECRET);const r=await oldFetch(`http://127.0.0.1:${server.address().port}/api/owner/12/upload`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});if(r.status!==201)console.log(await r.clone().text());assert.equal(r.status,201);assert.ok(captured);const hosted=Buffer.from(await captured.get('file').arrayBuffer());assert.ok(hosted.length<buffer.length);assert.match(captured.get('fileName'),/\.webp$/);const meta=await sharp(hosted).metadata();assert.equal(meta.width,2000);assert.equal(meta.hasAlpha,true);
 }finally{server.close();Business.findOne=oldFind;User.findByPk=oldUser;global.fetch=oldFetch;process.env.IMAGEKIT_PRIVATE_KEY=oldKey;}
});
