import React, {useEffect,useState} from 'react';
import {api} from '../lib/api.js';
export default function WhatsAppIntegration({token,storeId}) {
  const [status,setStatus]=useState(null),[messages,setMessages]=useState([]),[error,setError]=useState(''),[to,setTo]=useState(''),[text,setText]=useState(''),[review,setReview]=useState(null),[busy,setBusy]=useState(false);
  const root=`/owner/${storeId}/whatsapp-cloud`;
  async function refresh(){
    setError('');
    try {const s=await api(`${root}/status`,{token});setStatus(s);if(s.inboxEnabled){const data=await api(`${root}/messages`,{token});setMessages(data.messages);}}
    catch(e){setError(e.message);}
  }
  useEffect(()=>{setStatus(null);setMessages([]);setReview(null);refresh();},[token,storeId]);
  async function send(){
    if(!review||busy)return;setBusy(true);setError('');
    try {const result=await api(`${root}/send`,{token,method:'POST',body:{...review}});setReview(null);setText('');if(result.message?.status==='unknown'||result.message?.status==='submitting')setError('Delivery is unconfirmed. Do not retry with a new request.');await refresh();}
    catch(e){setError(e.message);setReview(null);}finally{setBusy(false);}
  }
  return <div className="dashboard-panel"><h3>WhatsApp production connection</h3><p>Reply to people who have messaged the connected shop number in the past 24 hours. These text replies are free. Paid templates, auto-replies and campaigns are not enabled here.</p>{error&&<p className="notice error" role="alert">{error}</p>}{!status&&!error&&<p role="status">Loading connection...</p>}{status&&<><dl><dt>Connected number</dt><dd>{status.sender||'Not configured'}</dd><dt>Webhook</dt><dd style={{overflowWrap:'anywhere'}}>{status.callback||'Not configured'}</dd><dt>Signed events</dt><dd>{status.cloudEnabled?'Enabled':'Disabled'}</dd><dt>Outbound replies</dt><dd>{status.outboundEnabled?'Configured. Delivery still depends on Meta and the service window.':'Not ready'}</dd><dt>Inbox storage</dt><dd>{status.inboxEnabled?'Enabled':'Not configured'}</dd></dl><button className="btn" onClick={refresh} disabled={busy}>Refresh inbox</button><h4>Messages</h4>{!messages.length&&<p>No messages stored yet.</p>}{messages.map(m=><article key={m.id} style={{borderBottom:'1px solid var(--line)',padding:'14px 0'}}><strong>{m.direction==='inbound'?'From':'To'} +{m.phone}</strong><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{m.text}</p><small>{new Date(m.eventAt).toLocaleString()} · {m.status}{m.errorCode?` (${m.errorCode})`:''}</small>{m.direction==='inbound'&&<button className="btn" onClick={()=>{setTo(m.phone);setReview(null);}}>Reply</button>}</article>)}{status.outboundEnabled&&<><h4>Reply</h4><label>Recipient number with country code<input value={to} onChange={e=>{setTo(e.target.value);setReview(null);}} maxLength={15}/></label><label>Message<textarea value={text} onChange={e=>{setText(e.target.value);setReview(null);}} maxLength={4096}/></label><button className="btn" disabled={busy||!text.trim()||!/^[1-9]\d{7,14}$/.test(to)} onClick={()=>setReview({to,text:text.trim(),requestId:crypto.randomUUID()})}>Review reply</button>{review&&<section style={{border:'1px solid var(--line)',padding:18,marginTop:16}}><h4>Send to +{review.to}</h4><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{review.text}</p><p>A recent inbound message is required. No paid template will be sent. An accepted message is not proof of delivery.</p><button className="btn" onClick={send} disabled={busy}>{busy?'Sending...':'Send this reply'}</button><button className="btn" disabled={busy} onClick={()=>setReview(null)}>Cancel</button></section>}</>}</>}</div>;
}
