import React,{useEffect,useState,useRef} from 'react';
import {api,download,inr} from '../../shared/lib/api.js';
import {Notice} from '../../shared/components/chrome.jsx';
import LoadSkeleton from '../../shared/components/LoadSkeleton.jsx';
import '../dashboard/sales-dashboard.css';
const istToday=()=>new Date(Date.now()+330*60000).toISOString().slice(0,10);
export default function PlatformSales({token}) {
 const today=istToday();
 const [filter,setFilter]=useState({from:today.slice(0,7)+'-01',to:today,storeId:'',ownerId:''}),[report,setReport]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState('');
 const [rule,setRule]=useState({businessId:'',percent:'0',effectiveFrom:today}),[review,setReview]=useState(false);
 const seq=useRef(0);
 const query=new URLSearchParams(Object.entries(filter).filter(([,v])=>v)).toString();
 const load=async()=>{const n=++seq.current;setLoading(true);setError('');try {const data=await api(`/admin/sales?${query}`,{token});if(n===seq.current)setReport(data);}catch(e){if(n===seq.current)setError(e.message);}finally{if(n===seq.current)setLoading(false);}};
 useEffect(()=>{load();},[query]);
 const set=(k,v)=>setFilter(f=>({...f,[k]:v}));
 const period=kind=>{let from=today,to=today;if(kind==='month')from=today.slice(0,7)+'-01';if(kind==='year')from=today.slice(0,4)+'-01-01';if(kind==='all')from=to='';setFilter(f=>({...f,from,to}));};
 const saveRule=async()=>{setBusy(true);setError('');try{await api('/admin/commission-rules',{token,method:'POST',body:{...rule,businessId:Number(rule.businessId),percent:Number(rule.percent)}});setSuccess('Commission rate saved. This records an estimate only; no store was charged.');setReview(false);await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const t=report?.totals||{},selected=report?.stores.find(s=>String(s.id)===rule.businessId);
 return <div className="platform-sales"><Notice error={error} success={success}/>
 <section className="dashboard-panel"><div className="leads-head"><div><h3>Sales across your stores</h3><p className="muted">Completed orders only. Day, month, year or your own period, in Indian time.</p></div><button className="btn btn-outline btn-small" disabled={busy||loading} onClick={async()=>{setBusy(true);try{await download(`/admin/sales/report.csv?${query}`,'platform-sales.csv',token);}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'Working...':'Download CSV'}</button></div>
 <div className="filter-tabs">{[['today','Today'],['month','This month'],['year','This year'],['all','All time']].map(([k,l])=><button key={k} onClick={()=>period(k)}>{l}</button>)}</div>
 <div className="platform-sales-filters"><label>Any month<input type="month" onChange={e=>{const v=e.target.value;if(v){const [y,m]=v.split('-').map(Number);const last=new Date(Date.UTC(y,m,0)).getUTCDate();setFilter(f=>({...f,from:v+'-01',to:v+'-'+last}));}}}/></label><label>Any year<input type="number" placeholder="e.g. 2026" min="2000" max="2100" onChange={e=>{const y=e.target.value;if(/^20\d{2}$/.test(y))setFilter(f=>({...f,from:y+'-01-01',to:y+'-12-31'}));}}/></label></div>
 <div className="platform-sales-filters"><label>From (IST)<input type="date" value={filter.from} onChange={e=>set('from',e.target.value)}/></label><label>Through (IST)<input type="date" value={filter.to} onChange={e=>set('to',e.target.value)}/></label><label>Owner / admin<select value={filter.ownerId} onChange={e=>setFilter(f=>({...f,ownerId:e.target.value,storeId:''}))}><option value="">All owners</option>{report?.owners.map(o=><option key={o.id} value={o.id}>{o.name} - {o.email}</option>)}</select></label><label>Store<select value={filter.storeId} onChange={e=>set('storeId',e.target.value)}><option value="">All stores</option>{report?.allStores.filter(s=>!filter.ownerId||String(s.ownerId)===filter.ownerId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div></section>
 {loading ? <LoadSkeleton label="Loading platform sales" cards={4} rows={3}/> : report && <>
 <div className="sd-kpis">{[['Recorded sales',inr(t.sales),'Completed/fulfilled order totals'],['Today (IST)',inr(t.today),'Recorded sales created today'],['This month (IST)',inr(t.month),'Recorded sales created this month'],['Completed orders',t.completed,'Delivered, completed or served'],['Pending requests',t.requests,`${inr(t.pendingValue)} requested, not sales`],['Commission estimate',inr(t.commission),'Not billed or collected']].map(([title,value,note])=><div className="sd-kpi" key={title}><span className="sd-kpi-title">{title}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
 <p className="notice">{report.caveat}</p>
 <section className="dashboard-panel table-wrap"><h3>Store and owner breakdown</h3><table><thead><tr><th>Store / owner</th><th>Completed</th><th>Recorded sales</th><th>Paid flag</th><th>Pending / cancelled</th><th>Commission estimate</th></tr></thead><tbody>{report.stores.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.ownerName}<br/>{s.ownerEmail}</small></td><td>{s.completed}</td><td>{inr(s.sales)}</td><td>{inr(s.paidSales)}</td><td>{s.requests} pending / {s.cancelled} cancelled</td><td>{inr(s.commission)}</td></tr>)}</tbody></table>{!report.stores.length&&<p className="empty-state">No stores match these filters.</p>}</section>
 <div className="platform-sales-grid"><section className="dashboard-panel table-wrap"><h3>Products sold</h3><p className="muted">Completed orders. Item value is before order discounts and delivery.</p><table><thead><tr><th>Product / store</th><th>Units</th><th>Item value</th></tr></thead><tbody>{report.products.map((p,i)=><tr key={i}><td><strong>{p.name}</strong><small>{p.storeName}</small></td><td>{p.units}</td><td>{inr(p.itemValue)}</td></tr>)}</tbody></table>{!report.products.length&&<p className="empty-state">No completed product sales in this period.</p>}</section>
 <section className="dashboard-panel table-wrap"><h3>Daily sales (IST)</h3><table><thead><tr><th>Day</th><th>Orders</th><th>Sales</th><th>Commission</th></tr></thead><tbody>{report.daily.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.orders}</td><td>{inr(d.sales)}</td><td>{inr(d.commission)}</td></tr>)}</tbody></table>{!report.daily.length&&<p className="empty-state">No recorded sales in this period.</p>}</section></div>
 <section className="dashboard-panel"><h3>Commission terms</h3><p className="muted">Default is 0%. Set an agreed store percentage and effective date. Older rate records are kept; calculations use each order's creation date. No payment request, deduction or collection happens here. Agree the terms with the owner before setting a rate.</p>
 <div className="platform-sales-filters"><label>Store<select value={rule.businessId} onChange={e=>{setReview(false);setRule(f=>({...f,businessId:e.target.value}));}}><option value="">Choose a store</option>{report.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Commission %<input type="number" min="0" max="100" step="0.01" value={rule.percent} onChange={e=>{setReview(false);setRule(f=>({...f,percent:e.target.value}));}}/></label><label>Effective from (IST)<input type="date" value={rule.effectiveFrom} onChange={e=>{setReview(false);setRule(f=>({...f,effectiveFrom:e.target.value}));}}/></label><button className="btn btn-green" disabled={busy||!rule.businessId||rule.percent===''} onClick={()=>setReview(true)}>Review rate</button></div>
 {review&&<div className="remove-confirm" role="alertdialog" aria-label="Review commission rate"><p>Save <strong>{rule.percent}%</strong> for <strong>{selected?.name}</strong> from <strong>{rule.effectiveFrom}</strong>? This changes commission estimates for orders created on or after this date, until a later rule applies. It does not charge the owner.</p><button className="btn btn-outline btn-small" onClick={()=>setReview(false)}>Cancel</button><button className="btn btn-green btn-small" disabled={busy} onClick={saveRule}>{busy?'Saving...':'Save agreed rate'}</button></div>}
 <div className="table-wrap"><table><thead><tr><th>Store</th><th>Rate</th><th>Effective from</th><th>Saved at</th></tr></thead><tbody>{report.rules.map(r=><tr key={r.id}><td>{report.stores.find(s=>s.id===r.businessId)?.name}</td><td>{r.percent}%</td><td>{r.effectiveFrom}</td><td>{new Date(r.createdAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td></tr>)}</tbody></table>{!report.rules.length&&<p className="muted">No commission terms saved. All stores currently calculate at 0%.</p>}</div>
 </section></>}
 </div>;
}
