import { productCsvTemplate, downloadProductCsv } from './product-csv.js';
import React, {useEffect,useState} from 'react';
import {api} from '../../shared/lib/api.js';
import {parseCsv} from './parse-csv.js';
import {IMPORT_FIELDS,suggestMapping,mapRows} from './column-mapping.js';
import {useFeedbackState} from '../../shared/components/Toasts.jsx';
export default function MappedImport({kind,token,storeId,onImported}){
 const [raw,setRaw]=useState(null),[mapping,setMapping]=useState({}),[preview,setPreview]=useState(null),[mapped,setMapped]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useFeedbackState(''),[result,setResult]=useState('');
 const fields=IMPORT_FIELDS[kind],headers=Object.keys(raw?.[0] || {});
 useEffect(()=>{setRaw(null);setPreview(null);setMapped(null);setResult('');setError('');},[storeId,kind]);
 const task=async fn=>{if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const choose=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;task(async()=>{
  if(file.size>2*1024*1024)throw Error('Choose a file under 2 MB.');let rows;
  if(/\.csv$/i.test(file.name))rows=parseCsv(await file.text());
  else if(/\.xlsx$/i.test(file.name)){const ExcelJS=(await import('exceljs')).default;const b=new ExcelJS.Workbook();await b.xlsx.load(await file.arrayBuffer());const sheet=b.worksheets[0];if(!sheet)throw Error('Workbook is empty.');const heads=sheet.getRow(1).values.slice(1).map(v=>String(v||'').trim());if(heads.some(h=>!h)||new Set(heads).size!==heads.length)throw Error('Each file column needs a unique header.');rows=[];sheet.eachRow((row,n)=>{if(n>1){const r=Object.fromEntries(heads.map((h,i)=>[h,row.getCell(i+1).text]));if(Object.values(r).some(Boolean))rows.push(r);}});}
  else throw Error('Choose CSV or XLSX.');if(!rows.length||rows.length>500)throw Error('Import 1-500 rows at a time.');setRaw(rows);setMapping(suggestMapping(Object.keys(rows[0]),fields));setPreview(null);setResult('');
 });};
 const review=()=>task(async()=>{const rows=mapRows(raw,mapping,fields);const p=await api(`/owner/${storeId}/${kind}/import/preview`,{token,method:'POST',body:{rows}});setMapped(rows);setPreview(p);});
 const commit=()=>task(async()=>{const r=await api(`/owner/${storeId}/${kind}/import/commit`,{token,method:'POST',body:{rows:mapped,digest:preview.digest}});setResult(`${r.created} added; ${r.skipped} existing rows skipped.`);setRaw(null);setPreview(null);onImported?.();});
 return <section className="dashboard-panel mapped-import"><h3>Import {kind}</h3><p className="muted">Match the file's columns to your store's fields. Preview and fix errors before importing. Existing records are skipped, not overwritten.{kind==='customers'?' Marketing consent is never imported or inferred.':''}</p>{kind==='products' && <><button type="button" className="btn btn-outline" onClick={()=>downloadProductCsv(productCsvTemplate(),'product-import-example.csv')}>Download example CSV</button><p className="muted">CSV fields: name, price, stock, category, description. Blank stock means unlimited. Replace the example row before import. Images, options and visibility are managed separately.</p></>}<label className="btn btn-outline btn-file">Choose CSV/XLSX<input hidden type="file" accept=".csv,.xlsx" disabled={busy} onChange={choose}/></label>{error&&<p className="notice error">{error}</p>}{result&&<p className="notice success">{result}</p>}{raw&&<><h4>Column mapping · {raw.length} {raw.length === 1 ? 'row' : 'rows'}</h4><div className="mapping-grid">{fields.map(f=><label key={f.key}>{f.label}{f.required?' *':''}<select value={mapping[f.key] || ''} disabled={busy} onChange={e=>{setMapping({...mapping,[f.key]:e.target.value});setPreview(null);setMapped(null);}}><option value="">{f.required?'Choose a column':'Ignore this field'}</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select><small>Sample: {mapping[f.key]?String(raw[0][mapping[f.key]]).slice(0,80):'Not mapped'}</small></label>)}</div><p className="muted">Unmapped file columns are ignored. Suggested matches are only suggestions; confirm them here.</p><button className="btn btn-green" disabled={busy} onClick={review}>{busy?'Working...':'Validate and preview'}</button><button className="btn btn-outline" disabled={busy} onClick={()=>{setRaw(null);setPreview(null);}}>Cancel</button></>}{preview&&<><h4>Nothing imported yet</h4><p>{preview.newCount} new · {preview.existingCount ?? preview.duplicateCount} existing · {preview.errors.length} errors</p>{preview.errors.map((e,i)=><p className="notice error" key={i}>Row {e.row}: {e.error}</p>)}<div className="table-wrap"><table><thead><tr>{fields.map(f=><th key={f.key}>{f.label}</th>)}<th>Action</th></tr></thead><tbody>{preview.preview.map((row,i)=><tr key={i}>{fields.map(f=><td key={f.key}>{String(row[f.key] ?? '')}</td>)}<td>{row.action}</td></tr>)}</tbody></table></div><button className="btn btn-green" disabled={busy||!!preview.errors.length} onClick={commit}>Import these {kind}</button></>}</section>;
}
